"""add_cascade

Revision ID: 31a1dc001e95
Revises: c416ef478b21
Create Date: 2025-02-17 22:05:07.748712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a1dc001e95'
down_revision = 'c416ef478b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'states', ['fg_states_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['fg_users_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['fg_users_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'states', ['fg_states_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
