"""add: data_retorno

Revision ID: 4cde10451a8c
Revises: 78bcf51ce612
Create Date: 2025-01-27 23:23:06.220963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde10451a8c'
down_revision = '78bcf51ce612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_retorno', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacations', schema=None) as batch_op:
        batch_op.drop_column('data_retorno')

    # ### end Alembic commands ###
