"""dbnovo

Revision ID: 78bcf51ce612
Revises: 295e594b2925
Create Date: 2025-01-25 22:00:59.791888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78bcf51ce612'
down_revision = '295e594b2925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_telefone', ['telefone'])
        batch_op.create_unique_constraint('uq_users_email', ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_telefone', type_='unique')
        batch_op.drop_constraint('uq_users_email', type_='unique')


    # ### end Alembic commands ###
