"""Corrigir relação de chave estrangeira entre vacations e user

Revision ID: 95cbfcea4075
Revises: fe3d16b2c73b
Create Date: 2025-01-20 22:06:02.420838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cbfcea4075'
down_revision = 'fe3d16b2c73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('military_id', sa.String(length=30), nullable=False),
    sa.Column('posto_grad', sa.String(length=30), nullable=False),
    sa.Column('nome_completo', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('dias_disp', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('military_id'),
    sa.UniqueConstraint('nome_completo')
    )
    op.create_table('vacations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('destino', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Ferias')
    op.drop_table('Usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('military_id', sa.VARCHAR(length=30), nullable=False),
    sa.Column('posto_grad', sa.VARCHAR(length=30), nullable=False),
    sa.Column('nome_completo', sa.VARCHAR(length=30), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('nivel', sa.INTEGER(), nullable=False),
    sa.Column('dias_disp', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('military_id'),
    sa.UniqueConstraint('nome_completo')
    )
    op.create_table('Ferias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('data_inicio', sa.DATE(), nullable=False),
    sa.Column('data_fim', sa.DATE(), nullable=False),
    sa.Column('destino', sa.VARCHAR(length=30), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dias', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vacations')
    op.drop_table('user')
    # ### end Alembic commands ###
