"""criacao do db

Revision ID: ae49f3efd9f6
Revises: 
Create Date: 2025-01-22 23:34:50.135094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae49f3efd9f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abrev', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abrev', sa.String(length=50), nullable=False),
    sa.Column('posto', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abrev', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('military_id', sa.String(length=30), nullable=False),
    sa.Column('nome_completo', sa.String(length=30), nullable=False),
    sa.Column('nome_guerra', sa.String(length=30), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('dias_disp', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('fg_secao_id', sa.Integer(), nullable=False),
    sa.Column('fg_organization_id', sa.Integer(), nullable=False),
    sa.Column('fg_patente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fg_organization_id'], ['organizacoes.id'], ),
    sa.ForeignKeyConstraint(['fg_patente_id'], ['patentes.id'], ),
    sa.ForeignKeyConstraint(['fg_secao_id'], ['secoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('military_id'),
    sa.UniqueConstraint('nome_completo')
    )
    op.create_table('vacations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('destino', sa.String(length=30), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('fg_users_id', sa.Integer(), nullable=False),
    sa.Column('fg_states_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fg_states_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['fg_users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacations')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('secoes')
    op.drop_table('patentes')
    op.drop_table('organizacoes')
    # ### end Alembic commands ###
